set GLSLC=C:\VulkanSDK\1.4.335.0\Bin\glslc.exe
set REFLECT=build\Debug\bin\spirv_reflect_tool.exe
set SPV_DIR=lumina\data\shaders\spv
set GEN_DIR=lumina\data\shaders\generated
set IFACE_DIR=lumina\data\shaders\interfaces
set MANIFEST=%GEN_DIR%\shaders_manifest.gen.hpp

if not exist %SPV_DIR% mkdir %SPV_DIR%
if not exist %GEN_DIR% mkdir %GEN_DIR%

:: ============================================================
:: Step 1: Reflect interfaces
:: Writes a temporary wrapper (version + include + stub main),
:: compiles to SPIR-V with -O0 (no dead-code removal), reflects,
:: then deletes the temp file.
:: ============================================================

set TMP_DIR=%TEMP%\lumina_reflect_tmp
if not exist %TMP_DIR% mkdir %TMP_DIR%

:: standard_lit vertex
(echo #version 450)                                         > %TMP_DIR%\standard_lit.vert.glsl.reflect
(echo #include "standard_lit.vert.glsl")                   >> %TMP_DIR%\standard_lit.vert.glsl.reflect
(echo void main^(^) { gl_Position = vec4^(0.0^); })        >> %TMP_DIR%\standard_lit.vert.glsl.reflect
%GLSLC% -fshader-stage=vertex -O0 -I %IFACE_DIR% -o %TMP_DIR%\standard_lit.vert.spv %TMP_DIR%\standard_lit.vert.glsl.reflect
%REFLECT% %TMP_DIR%\standard_lit.vert.spv %GEN_DIR%\standard_lit.vert.gen.hpp
del %TMP_DIR%\standard_lit.vert.glsl.reflect
del %TMP_DIR%\standard_lit.vert.spv

:: standard_lit fragment
(echo #version 450)                                         > %TMP_DIR%\standard_lit.frag.glsl.reflect
(echo #include "standard_lit.frag.glsl")                   >> %TMP_DIR%\standard_lit.frag.glsl.reflect
(echo void main^(^) {})                                    >> %TMP_DIR%\standard_lit.frag.glsl.reflect
%GLSLC% -fshader-stage=fragment -O0 -I %IFACE_DIR% -o %TMP_DIR%\standard_lit.frag.spv %TMP_DIR%\standard_lit.frag.glsl.reflect
%REFLECT% %TMP_DIR%\standard_lit.frag.spv %GEN_DIR%\standard_lit.frag.gen.hpp
del %TMP_DIR%\standard_lit.frag.glsl.reflect
del %TMP_DIR%\standard_lit.frag.spv

rmdir /s /q %TMP_DIR%

:: ============================================================
:: Step 2: Compile shader implementations (no reflection needed)
:: ============================================================

%GLSLC% -fshader-stage=vertex   -o %SPV_DIR%\shader.vert.spv lumina\data\shaders\src\shader.vert
%GLSLC% -fshader-stage=fragment -o %SPV_DIR%\shader.frag.spv lumina\data\shaders\src\shader.frag

:: ============================================================
:: Step 3: Generate shaders_manifest.gen.hpp
:: One file with all shader programs: runtime array + typed structs.
::
:: To add a new shader:
::   1. Add a line to the kPrograms[] array
::   2. Add a struct in the programs:: namespace
:: To add a new interface:
::   1. Add its reflect step above in Step 1
::   2. Add its #include below
:: ============================================================

echo #pragma once> %MANIFEST%
echo // Auto-generated by sc.bat -- do not edit.>> %MANIFEST%
echo.>> %MANIFEST%

:: --- One include per unique interface used ---
echo #include "standard_lit.vert.gen.hpp">> %MANIFEST%
echo #include "standard_lit.frag.gen.hpp">> %MANIFEST%
echo.>> %MANIFEST%

echo namespace lumina::shaders {>> %MANIFEST%
echo.>> %MANIFEST%

echo struct ShaderProgramDesc {>> %MANIFEST%
echo   const char* name;>> %MANIFEST%
echo   const char* vert_spv;>> %MANIFEST%
echo   const char* frag_spv;>> %MANIFEST%
echo };>> %MANIFEST%
echo.>> %MANIFEST%

:: --- Runtime-enumerable array of all programs ---
echo inline constexpr ShaderProgramDesc kPrograms[] = {>> %MANIFEST%
echo   { "shader", "spv/shader.vert.spv", "spv/shader.frag.spv" },>> %MANIFEST%
echo };>> %MANIFEST%
echo.>> %MANIFEST%

:: --- Typed per-program structs for compile-time interface association ---
echo namespace programs {>> %MANIFEST%
echo.>> %MANIFEST%

echo struct Shader {>> %MANIFEST%
echo   using Vert = standard_lit::vert;>> %MANIFEST%
echo   using Frag = standard_lit::frag;>> %MANIFEST%
echo   static constexpr auto kVertSpv = "spv/shader.vert.spv";>> %MANIFEST%
echo   static constexpr auto kFragSpv = "spv/shader.frag.spv";>> %MANIFEST%
echo };>> %MANIFEST%
echo.>> %MANIFEST%

echo } // namespace programs>> %MANIFEST%
echo } // namespace lumina::shaders>> %MANIFEST%

pause
