#pragma once
// Auto-generated by spirv_reflect_tool — do not edit.

#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "renderer/shaders/shader_layout.hpp"

namespace lumina::shaders::color_output::frag {
static constexpr lumina::renderer::ShaderLayout kLayout = {
    .stage = lumina::renderer::ShaderStage::Fragment,
    .binding_count = 0,
    .bindings = nullptr,
    .push_constant_size = 0,
    .push_constant_offset = 0,
    .vertex_input_layout = {}};
} // namespace lumina::shaders::color_output::frag
