#pragma once
// Auto-generated by spirv_reflect_tool — do not edit.

#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "renderer/shaders/shader_layout.hpp"
#include <vulkan/vulkan.h>

namespace lumina::shaders::interface::global {
struct PointLight {
  lumina::math::Vec3 position;
  float intensity;
  lumina::math::Vec3 color;
  float attenuation_radius;
}; // struct PointLight

struct FrameGlobals {
  lumina::math::Mat4 view;
  lumina::math::Mat4 proj;
  PointLight point_lights[16];
  lumina::math::Vec3 camera_position;
  int32_t point_light_count;
}; // struct FrameGlobals

struct PushConstants {
  lumina::math::Mat4 model;
}; // struct PushConstants

static constexpr lumina::renderer::ShaderBindingInfo kBindings[] = {
    {.set = 0,
     .binding = 0,
     .type = lumina::renderer::DescriptorBindingType::UniformBuffer,
     .name = "frame_globals",
     .block_size = sizeof(FrameGlobals),
     .array_count = 1}};

static constexpr lumina::renderer::ShaderLayout kLayout = {
    .stage = lumina::renderer::ShaderStage::Global,
    .binding_count = 1,
    .bindings = kBindings,
    .push_constant_size = sizeof(PushConstants),
    .push_constant_offset = 0,
    .vertex_input_layout = {}};

struct BindingData {
  VkBuffer frame_globals_buffer;
  VkDeviceSize frame_globals_offset = 0;
  VkDeviceSize frame_globals_range = sizeof(FrameGlobals);
}; // struct BindingData

inline void WriteDescriptors(VkDevice device, VkDescriptorSet set,
                             const BindingData &data) {
  VkDescriptorBufferInfo buffer_info_0{
      .buffer = data.frame_globals_buffer,
      .offset = data.frame_globals_offset,
      .range = data.frame_globals_range,
  };
  VkWriteDescriptorSet writes[] = {
      {
          .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
          .dstSet = set,
          .dstBinding = 0,
          .descriptorCount = 1,
          .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
          .pBufferInfo = &buffer_info_0,
      },
  };
  vkUpdateDescriptorSets(device, 1, writes, 0, nullptr);
}
} // namespace lumina::shaders::interface::global
