#pragma once
// Auto-generated by spirv_reflect_tool — do not edit.

#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "renderer/shaders/shader_layout.hpp"
#include <vulkan/vulkan.h>

namespace lumina::shaders::screen2d::global {
static constexpr lumina::renderer::ShaderBindingInfo kBindings[] = {
    {.set = 0,
     .binding = 0,
     .type = lumina::renderer::DescriptorBindingType::CombinedImageSampler,
     .name = "font_atlas",
     .block_size = 0,
     .array_count = 1}};

static constexpr lumina::renderer::ShaderLayout kLayout = {
    .stage = lumina::renderer::ShaderStage::Global,
    .binding_count = 1,
    .bindings = kBindings,
    .push_constant_size = 0,
    .push_constant_offset = 0,
    .vertex_input_layout = {}};

struct BindingData {
  VkSampler font_atlas_sampler;
  VkImageView font_atlas_imageView;
  VkImageLayout font_atlas_imageLayout =
      VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
}; // struct BindingData

inline void WriteDescriptors(VkDevice device, VkDescriptorSet set,
                             const BindingData &data) {
  VkDescriptorImageInfo image_info_0{
      .sampler = data.font_atlas_sampler,
      .imageView = data.font_atlas_imageView,
      .imageLayout = data.font_atlas_imageLayout,
  };
  VkWriteDescriptorSet writes[] = {
      {
          .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
          .dstSet = set,
          .dstBinding = 0,
          .descriptorCount = 1,
          .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
          .pImageInfo = &image_info_0,
      },
  };
  vkUpdateDescriptorSets(device, 1, writes, 0, nullptr);
}
} // namespace lumina::shaders::screen2d::global
