#pragma once
// Auto-generated by spirv_reflect_tool — do not edit.

#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "renderer/shaders/shader_layout.hpp"

namespace lumina::shaders::interface::global {
struct UniformBufferObject {
  lumina::math::Mat4 view;
  lumina::math::Mat4 proj;
}; // struct UniformBufferObject

struct PushConstants {
  lumina::math::Mat4 model;
}; // struct PushConstants

static constexpr lumina::renderer::ShaderBindingInfo kBindings[] = {
    {.set = 0,
     .binding = 0,
     .type = lumina::renderer::DescriptorBindingType::UniformBuffer,
     .name = "ubo",
     .block_size = sizeof(UniformBufferObject),
     .array_count = 1}};

static constexpr lumina::renderer::ShaderLayout kLayout = {
    .stage = lumina::renderer::ShaderStage::Global,
    .binding_count = 1,
    .bindings = kBindings,
    .push_constant_size = sizeof(PushConstants),
    .push_constant_offset = 0,
    .vertex_input_layout = {}};
} // namespace lumina::shaders::interface::global
