#pragma once
// Auto-generated by spirv_reflect_tool — do not edit.

#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "renderer/shaders/shader_layout.hpp"
#include <vulkan/vulkan.h>

namespace lumina::shaders::simple_input_basic_mat::frag {
struct MaterialUniforms {
  float ambient_intensity;
  uint8_t _pad0[12];
  lumina::math::Vec3 ambient_color;
  uint8_t _pad1[4];
  lumina::math::Vec3 diffuse_color;
  uint8_t _pad2[4];
}; // struct MaterialUniforms

static constexpr lumina::renderer::ShaderBindingInfo kBindings[] = {
    {.set = 1,
     .binding = 0,
     .type = lumina::renderer::DescriptorBindingType::CombinedImageSampler,
     .name = "texSampler",
     .block_size = 0,
     .array_count = 1},
    {.set = 1,
     .binding = 1,
     .type = lumina::renderer::DescriptorBindingType::UniformBuffer,
     .name = "material_uniforms",
     .block_size = sizeof(MaterialUniforms),
     .array_count = 1}};

static constexpr lumina::renderer::ShaderLayout kLayout = {
    .stage = lumina::renderer::ShaderStage::Fragment,
    .binding_count = 2,
    .bindings = kBindings,
    .push_constant_size = 0,
    .push_constant_offset = 0,
    .vertex_input_layout = {}};

struct BindingData {
  VkSampler texSampler_sampler;
  VkImageView texSampler_imageView;
  VkImageLayout texSampler_imageLayout =
      VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;
  VkBuffer material_uniforms_buffer;
  VkDeviceSize material_uniforms_offset = 0;
  VkDeviceSize material_uniforms_range = sizeof(MaterialUniforms);
}; // struct BindingData

inline void WriteDescriptors(VkDevice device, VkDescriptorSet set,
                             const BindingData &data) {
  VkDescriptorImageInfo image_info_0{
      .sampler = data.texSampler_sampler,
      .imageView = data.texSampler_imageView,
      .imageLayout = data.texSampler_imageLayout,
  };
  VkDescriptorBufferInfo buffer_info_1{
      .buffer = data.material_uniforms_buffer,
      .offset = data.material_uniforms_offset,
      .range = data.material_uniforms_range,
  };
  VkWriteDescriptorSet writes[] = {
      {
          .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
          .dstSet = set,
          .dstBinding = 0,
          .descriptorCount = 1,
          .descriptorType = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
          .pImageInfo = &image_info_0,
      },
      {
          .sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
          .dstSet = set,
          .dstBinding = 1,
          .descriptorCount = 1,
          .descriptorType = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
          .pBufferInfo = &buffer_info_1,
      },
  };
  vkUpdateDescriptorSets(device, 2, writes, 0, nullptr);
}
} // namespace lumina::shaders::simple_input_basic_mat::frag
