#pragma once
// Auto-generated by spirv_reflect_tool — do not edit.

#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "renderer/shaders/shader_layout.hpp"

namespace lumina::shaders::standard_lit::vert {
static constexpr lumina::renderer::VertexInputInfo kVertexInputs[] = {
    {.location = 0,
     .attribute_type = lumina::core::VertexAttributeType::Position,
     .element_type = lumina::core::ElementType::Vec3},
    {.location = 1,
     .attribute_type = lumina::core::VertexAttributeType::Color,
     .element_type = lumina::core::ElementType::Vec3},
    {.location = 2,
     .attribute_type = lumina::core::VertexAttributeType::TexCoord,
     .element_type = lumina::core::ElementType::Vec2}};

static constexpr lumina::renderer::ShaderLayout kLayout = {
    .stage = lumina::renderer::ShaderStage::Vertex,
    .binding_count = 0,
    .bindings = nullptr,
    .push_constant_size = 0,
    .push_constant_offset = 0,
    .vertex_input_layout = {.input_count = 3, .inputs = kVertexInputs}};
} // namespace lumina::shaders::standard_lit::vert
