#pragma once
// Auto-generated by spirv_reflect_tool — do not edit.

#include "math/matrix.hpp"
#include "math/vector.hpp"
#include "renderer/shaders/shader_layout.hpp"

namespace lumina::shaders::standard_lit::frag {
static constexpr lumina::renderer::ShaderBindingInfo kBindings[] = {
    {.set = 1,
     .binding = 0,
     .type = lumina::renderer::DescriptorBindingType::CombinedImageSampler,
     .name = "texSampler",
     .block_size = 0,
     .array_count = 1}};

static constexpr lumina::renderer::ShaderLayout kLayout = {
    .stage = lumina::renderer::ShaderStage::Fragment,
    .binding_count = 1,
    .bindings = kBindings,
    .push_constant_size = 0,
    .push_constant_offset = 0,
    .vertex_input_layout = {}};
} // namespace lumina::shaders::standard_lit::frag
